@echo off

SETLOCAL ENABLEDELAYEDEXPANSION
set file=.\include\version.hpp
echo File = %file%
(
	echo // File generated by writeVersion.bat/sh. Do not modify
	echo #define GIT_HEAD "Unknown"
	echo #define GIT_LOG "Unknown"
	echo #define GIT_DIFF "Unknown"
) > %file%